apiVersion: v1
kind: PersistentVolumeClaim

{{- with .Values.pvc }}

metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    - {{ .accessModes }}
  resources:
    requests:
      storage: {{ .resource.requests.storage }}

{{- end }}
