apiVersion: v1
kind: Secret

{{- with .Values.secret }}

metadata:
  name: {{ .name }}-auth
data:
  password: {{ required "password is required in the helm arguments" .password | b64enc }}
  username: {{ required "username is required in the helm arugments" .username | b64enc }}
  root_password: {{ required "MySQL root password is required in the helm arugments" .root_password | b64enc }}

{{- end}}
