apiVersion: v1
kind: Service

{{- with .Values.service }}

metadata:
  name: {{ .name  }}
  namespace: {{ $.Values.global.namespace }}
spec:
  type: {{ .type }}
  selector:
    app: mariadb-database
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}

{{- end }}
