apiVersion: v1
kind: PersistentVolume

{{- with .Values.pv }}

metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  capacity:
    storage: {{ .capacity.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .accessModes }}
  persistentVolumeReclaimPolicy: {{ .reclaim }}
  storageClassName: {{ .storageClassName }}
  mountOptions:
    {{- range .mountOptions }}
    - {{ . }}
    {{- end  }}
  nfs:
    path: {{ .nfs.path }}
    server: {{ .nfs.server }}

{{- end}}
